const SCREENS = {
  CAMERA_ROLL: 'CAMERA_ROLL',
  CHART: 'CHART',
  CHART_LIBRARY: 'CHART_LIBRARY',
  LOGIN: 'LOGIN',
  MAIN: 'MAIN',
  REGISTRATION: 'REGISTRATION',
  SINGLE_IMAGE: 'SINGLE_IMAGE',
  UPLOAD: 'UPLOAD',
}

export default SCREENS
